// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBumQ8HUolBz3y-6ype3Fy49wqgUQjVFdk',
    appId: '1:1030310351612:web:23a9689f12a8cd3bf67d79',
    messagingSenderId: '1030310351612',
    projectId: 'projetocrud-3d576',
    authDomain: 'projetocrud-3d576.firebaseapp.com',
    storageBucket: 'projetocrud-3d576.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqF9ai8BdeeDf-mwaPETOFKByrjIzvy6E',
    appId: '1:1030310351612:android:5f33f5de6f8c4a2ff67d79',
    messagingSenderId: '1030310351612',
    projectId: 'projetocrud-3d576',
    storageBucket: 'projetocrud-3d576.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeU0BJoYtC__PGdAQqOzY0On7RZi0y2ss',
    appId: '1:1030310351612:ios:8fcb81cd25c5064ff67d79',
    messagingSenderId: '1030310351612',
    projectId: 'projetocrud-3d576',
    storageBucket: 'projetocrud-3d576.appspot.com',
    iosBundleId: 'com.example.projetocrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeU0BJoYtC__PGdAQqOzY0On7RZi0y2ss',
    appId: '1:1030310351612:ios:8fcb81cd25c5064ff67d79',
    messagingSenderId: '1030310351612',
    projectId: 'projetocrud-3d576',
    storageBucket: 'projetocrud-3d576.appspot.com',
    iosBundleId: 'com.example.projetocrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBumQ8HUolBz3y-6ype3Fy49wqgUQjVFdk',
    appId: '1:1030310351612:web:0f002fb6c932e0a8f67d79',
    messagingSenderId: '1030310351612',
    projectId: 'projetocrud-3d576',
    authDomain: 'projetocrud-3d576.firebaseapp.com',
    storageBucket: 'projetocrud-3d576.appspot.com',
  );
}
